### ISSUE TITLE
Performance regression with JRuby 9

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-diagram#214] opened 2019-02-11 20:19 UTC
I don't if we are doing something wrong here but AsciidoctorJ with Asciidoctor Diagram is noticeably slower with JRuby 9:

@SevereOverfl0w made a sample project to reproduce this issue. It's a Clojure project but it's relatively easy to run it (and it will generate a flamegraph!): https://github.com/SevereOverfl0w/asciidoctor-diagram-slow-repro

Once Clojure is installed you should be able to run `clojure -A:run`.

You should see somthing like:

```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
"Elapsed time: 1793.124807 msecs"
Producing flamegraph for 100 runs
Started [cpu] profiling
```

And the flamegraph will looks weird with spikes on Asciidoctor Diagram.

Now if you edit the `deps.edn` file and add `org.jruby/jruby-complete {:mvn/version "1.7.27"}` (just after `net.sourceforge.plantuml/plantuml {:mvn/version "1.2018.13"}`) then the output will be:

```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
"Elapsed time: 963.936468 msecs"
Producing flamegraph for 100 runs
Started [cpu] profiling
```

and the spikes on Asciidoctor Diagram are gone...

**Comment by pepijnve** [comment] 2019-02-11 20:22
🤔 weird...

Must be some Ruby code construct that JRuby doesn't like.

**Comment by Mogztter** [comment] 2019-02-11 20:48
Probably, do you reproduce this issue ? I can share flamegraph if you want

**Comment by pepijnve** [comment] 2019-02-11 20:50
I see the flamegraph, but it's not very useful to me to be honest. I know how to interpret these things, but there's no obvious hotspot that sticks out.

**Comment by pepijnve** [comment] 2019-02-11 20:52
FWIW, best I can make of it is that a lot of time is spent getting the mtime of files.

**Comment by pepijnve** [comment] 2019-02-12 15:30
@Mogztter I had another look at the flame graph with a clear head today. Which part of this do you think is problematic and why do you think asciidoctor-diagram specifically is to blame?

Just an open question; I don't see the problem. All of the time seems to be taken up loading the extensions themselves, but if you drill down on that the 'expensive' parts are calls to `require_relative`. Not sure there's much I can do about that.

**Comment by SevereOverfl0w** [comment] 2019-02-12 16:03
The require_relative calls weren't visible on the flame graph before switching to JRuby 9.

To compare:
[flame.zip](https://github.com/asciidoctor/asciidoctor-diagram/files/2856551/flame.zip)

(Sorry GitHub won't allow SVG uploads)

**Comment by pepijnve** [comment] 2019-02-12 16:14
@SevereOverfl0w fair enough, but kind of out of my control. If anything it looks like there's a performance regression with `require_relative` in jruby 9. Best I could do is replace `require_relative` with plain `require`.

**Comment by pepijnve** [comment] 2019-02-12 16:21
I'll take a shot at profiling this with JProfiler later this evening. Perhaps that clarifies the difference in performance between jruby 1.7 and 9. I'll let you know what I find (if anything).

**Comment by Mogztter** [comment] 2019-02-12 17:23
To clarify I'm not saying that Asciidoctor Diagram is doing something wrong or that we should not use `require_relative`. I've opened this issue so we can find the root cause, maybe it's JRuby maybe it's Asciidoctor Diagram, maybe it's an interaction between Clojure and the DynamicClasspath... who knows :wink: 

But before raising an issue upstream (JRuby) I think it's important to make sure that we didn't missed something.

I will try to create a minimal reproduction case (outside of Asciidoctor Diagram) using `require_relative`.

**Comment by pepijnve** [comment] 2019-02-12 20:49
Perhaps somewhat unsurprisingly, JProfiler says the same thing. Hotspots in sampling mode below. What's a bit surprising to see is how for every call to `readDocumentHeader` a new Class is defined at runtime. I started digging into why that's happening, but that rabbit hole is too deep; not enough time right now. I did find this in asciidoctorclass.rb which doesn't seem quite right.
```
class AsciidoctorModule
    java_implements Java::Asciidoctor
```
The `AsciidoctorModule` class is expected to be an implementation of `org.asciidoctor.internal.AsciidoctorModule`, not `Asciidoctor`. Anyway, might be a red herring.

JRuby 9
<img width="822" alt="jruby9" src="https://user-images.githubusercontent.com/225326/52666728-534bc400-2f0f-11e9-8cca-ef668e5ce985.png">

JRuby 1.7
<img width="976" alt="jruby17" src="https://user-images.githubusercontent.com/225326/52666576-f51ee100-2f0e-11e9-9027-4b68f657f36c.png">

**Comment by Mogztter** [comment] 2019-02-14 17:23
I've upgraded JRuby version to find when the performance regression has been introduced. Unfortunately AsciidoctorJ only work with JRuby >= 9.1.11.0+ but I found this commit: https://github.com/jruby/jruby/commit/7e7292e632bd66a95fed78b37e73d6e63f90d631

**Comment by Mogztter** [comment] 2019-02-14 17:38
```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
Elapsed time: 1667 msecs
Producing flamegraph for 100 runs
```

![realpath](https://user-images.githubusercontent.com/333276/52805695-6e414400-3087-11e9-9d38-f868b8912e6e.png)


If I remove the `File.realpath(file)`:

```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
Elapsed time: 842 msecs
Producing flamegraph for 100 runs
```

![require_relative](https://user-images.githubusercontent.com/333276/52805771-9b8df200-3087-11e9-86de-aba7c25c454f.png)

**Comment by Mogztter** [comment] 2019-02-14 17:50
Flamegraph: [flames.zip](https://github.com/asciidoctor/asciidoctor-diagram/files/2866222/flames.zip)

**Comment by pepijnve** [comment] 2019-02-14 19:19
Great find @mogztter. I think we have a winner.
So conclusion is that require_relative has hidden costs. Best way to fix this then is to just use require instead I guess. Easy enough to fix.
Nice tag teaming going on here! 💪

**Comment by headius** [comment] 2019-02-14 19:23
Short term, yes it would be easiest to just use require. However I'm going to open an issue in JRuby to improve the perf of require_relative now.

**Comment by mojavelinux** [comment] 2019-02-14 20:41
Fantastic work @Mogztter. I appreciate you tracking that down!

**Comment by mojavelinux** [comment] 2019-02-14 20:46
@Mogztter You are correct that the extensions block is run on every call to convert. However, it seems odd to me that `require_relative` is called each time (at least beyond the top call). I thought that require statements are called once per runtime, then skipped all other times.

@pepijnve Another option is to use require with an absolute path. That way, it hits the same file, but bypasses the require_relative logic.

We just switched to using require_relative everywhere in Asciidoctor core. I would expect these to run exactly once and then short-circuited all other times. Should I be concerned?

As for asciidoctorclass.rb, I believe that was created to work around an old limitation in JRuby. I'm not sure it's needed any more. JRuby should be able to invoke Asciidoctor.convert (and family) directly on the module. We should open an issue in AsciidoctorJ to track that down.

**Comment by headius** [comment] 2019-02-15 00:37
It looks like the File.realpath was done to support in-jar URLs (classloader resources) which have weird paths. The amount of work it's doing to support that seems a bit much.

require_relative should fire only once for each file.

**Comment by headius** [comment] 2019-02-15 01:22
I've pushed fixes to JRuby master that should reduce some of the overhead of `require_relative`. It does not address the use of `realpath` which is still needed to support relative requires from inside a jar (since they'll be classloader URIs).

**Comment by pepijnve** [comment] 2019-02-15 08:38
@mojavelinux per the require docs of `require`

> The absolute path of the loaded file is added to $LOADED_FEATURES ($"). A file will not be loaded again if its path already appears in $". For example, require 'a'; require './a' will not load a.rb again.

that implies that for every `require` or `require_relative` call you still need to to determine the final absolute path of the file being required which means there's a non-zero cost to calling `require`. I would expect `require_relative` to be the faster case since it avoids needing to scan the load path as the starting point is already an absolute path. `realpath` isn't free either of course...

@Mogztter since this is getting fixed (or at least improved) in jruby and asciidoctor proper is transitioning to `require_relative`, I'm inclined to leave things as is in asciidoctor-diagram. Is that ok for you? Or is performance unusably slow at the moment?

**Comment by Mogztter** [comment] 2019-02-15 09:38
> require_relative should fire only once for each file.

I will profile multiple executions of `asciidoctor.readDocumentHeader`.
So this method [1] should only be called once per file ? (and as a consequence the path resolution should only be called once per file ?)

I didn't find any reference to `LOADED_FEATURES` in the JRuby code (except in test/spec and in GlobalVariable) so I believe this logic is in Ruby [2] ?

Anyway I will add some breakpoints to better understand :wink: 

[1] https://github.com/jruby/jruby/blob/6a6252032cd24cf9c7b286ff7bdb6766dca7b989/core/src/main/java/org/jruby/RubyKernel.java#L997
[2] https://github.com/ruby/ruby/blob/d7c7382f7afcba2d74454b24f9d1b9bb761c7242/load.c#L989

**Comment by pepijnve** [comment] 2019-02-15 09:56
Just my intuition speaking, but I would expect you to end up here on every single call to require. https://github.com/jruby/jruby/blob/a67a9c5e2d702fbfc048653195ff9315fb30d06a/core/src/main/java/org/jruby/runtime/load/LoadService.java#L495

**Comment by Mogztter** [comment] 2019-02-15 22:24
I can confirm that the file is not loaded again but the `require_relative` method in `RubyKernel` is called 17 times on every `asciidoctor.readDocumentHeader` invocation.

The reason is that the extension registry contains:
 
```
0 = {RubyProc@8019} "#<Proc:0x2570b316@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/a2s.rb:3>"
1 = {RubyProc@8020} "#<Proc:0x56881196@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/blockdiag.rb:3>"
2 = {RubyProc@8021} "#<Proc:0x75c33608@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/ditaa.rb:3>"
3 = {RubyProc@8022} "#<Proc:0x25464154@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/erd.rb:3>"
4 = {RubyProc@8023} "#<Proc:0x58ebee9@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/graphviz.rb:3>"
5 = {RubyProc@8024} "#<Proc:0x131c0b6f@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/meme.rb:3>"
6 = {RubyProc@8025} "#<Proc:0x7f030c72@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/mermaid.rb:3>"
7 = {RubyProc@8026} "#<Proc:0x68d8ae27@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/msc.rb:3>"
8 = {RubyProc@8027} "#<Proc:0x18513c23@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/plantuml.rb:3>"
9 = {RubyProc@8028} "#<Proc:0x6be50b35@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/salt.rb:3>"
10 = {RubyProc@8029} "#<Proc:0xce2eaa7@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/shaape.rb:3>"
11 = {RubyProc@8030} "#<Proc:0x2166c48a@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/svgbob.rb:3>"
12 = {RubyProc@8031} "#<Proc:0x304744a1@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/syntrax.rb:3>"
13 = {RubyProc@8032} "#<Proc:0x73385d3f@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/tikz.rb:3>"
14 = {RubyProc@8033} "#<Proc:0x6814262d@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/umlet.rb:3>"
15 = {RubyProc@8034} "#<Proc:0x7fc1fd31@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/vega.rb:3>"
16 = {RubyProc@8035} "#<Proc:0x75a9cc24@uri:classloader:/gems/asciidoctor-diagram-1.5.12/lib/asciidoctor-diagram/wavedrom.rb:3>"
```

Asciidoctor will execute each block/proc to register the extension. And in each extension we are doing `require_relative 'extensions'`:

https://github.com/asciidoctor/asciidoctor-diagram/blob/505efba8142ff0e5bd1201457022fa304d6dfd04/lib/asciidoctor-diagram/a2s.rb#L1

So that's why it's slow because `expand_path` is called 17 times.

**Comment by Mogztter** [comment] 2019-02-15 22:26
@headius I can confirm that master branch is a bit faster:

```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
Elapsed time: 1479 msecs
Producing flamegraph for 100 runs
/tmp/clj-async-profiler/results/flamegraph-2019-02-15-23-25-31.svg
```

**Comment by pepijnve** [comment] 2019-02-16 09:17
@Mogztter @mojavelinux any recommendations/best practices on using `require` that you can recommend. At the moment I kind of use it like you would use `import` in Java or `#include` in C/C++. In other words, treat every file as a 'compilation unit' and require whatever the code in the file in question depends on. That obviously leads to a lot of duplicate requires, but avoids having a brittle require order.
No idea what the common practice in Ruby actually is...

**Comment by Mogztter** [comment] 2019-02-16 14:03
@pepijnve My previous comment was wrong, I think we should move `require_relative` outside the block:

#### Before

```rb
require_relative 'extensions'

Asciidoctor::Extensions.register do
  require_relative 'a2s/extension'

  block Asciidoctor::Diagram::AsciiToSvgBlockProcessor, :a2s
  block_macro Asciidoctor::Diagram::AsciiToSvgBlockMacroProcessor, :a2s
end
```

#### After

```rb
require_relative 'extensions'
require_relative 'a2s/extension'

Asciidoctor::Extensions.register do
  block Asciidoctor::Diagram::AsciiToSvgBlockProcessor, :a2s
  block_macro Asciidoctor::Diagram::AsciiToSvgBlockMacroProcessor, :a2s
end
```

Otherwise `require_relative 'a2s/extension'` will be resolved (the path) on every invocation.
Though I don't known if it's intended or not ?

@mojavelinux What do you think ?

**Comment by mojavelinux** [comment] 2019-02-16 19:25
Yes, absolutely. That aligns with what I was suggesting.

Another way to avoid require calls is to use a defined? guard. I do this a
lot in core. For example:

require 'asciimath' unless defined? AsciiMath.load

You look for a symbol that would be present if required has already been
called. This is extremely fast in my experience.

**Comment by pepijnve** [comment] 2019-02-18 20:44
@Mogztter dc3ba61 cleans up the require statements. Is it easy for you to check if this improves things in asciidoctorj?

**Comment by Mogztter** [comment] 2019-02-18 20:52
@pepijnve Good! Yep I will give it a try and let you know 👍

**Comment by Mogztter** [comment] 2019-02-24 22:46
Ooops sorry for the delay I will do it tomorrow 😉

**Comment by Mogztter** [comment] 2019-02-25 10:57
@pepijnve The code is now faster in JRuby 9:

```
Warming up JIT with 30 calls
Timing 100 calls of .readDocumentHeader
Elapsed time: 802 msecs
Producing flamegraph for 100 runs
/tmp/clj-async-profiler/results/flamegraph-2019-02-25-11-56-25.svg
```

**Comment by pepijnve** [comment] 2019-02-25 10:58
Fantastic! I'll make a new release then and with that I think we can consider this closed.

**Closed** 2019-02-25 11:02 UTC

**Comment by headius** [comment] 2019-03-13 13:25
My next big project for JRuby is to fix up the require/load caching logic, which should prevent this from affecting anyone in the future. Glad to see you found a good solution that is not hacky and makes sense anyway!
