### ISSUE TITLE
How to use this library in guard livereload script

### ISSUE THREAD

**Issue by gardenias** [asciidoctor/asciidoctor-diagram#200] opened 2018-11-05 11:10 UTC
Guardfile content
```
require 'asciidoctor'
require 'erb'
require 'fileutils'
require 'asciidoctor-diagram'

FileUtils.mkdir_p('build')
FileUtils.cp_r('images','build')
FileUtils.cp_r('tocbot-3.0.2','build')
FileUtils.cp_r('stylesheets','build')

guard 'shell' do
  watch(/^.*\.adoc$/) {|m|
  	if m[0] != "index.adoc"
  	Asciidoctor.render_file(m[0], :extensions=, :to_dir => "build", :safe => Asciidoctor::SafeMode::UNSAFE, :attributes=> {'sectnums'=>'','stylesheet'=>'main.css','stylesdir'=>'stylesheets/','icons' =>'font','idprefix' => '', 'idseparator' => '-', 'copycss' => '', 'source-highlighter' => 'coderay@', 'sectanchors' => '', 'doctype' => 'book', 'eruby'=>'erubis', 'toc' => 'left', 'toclevels' => '2', 'revnumber' => '1.0', 'require'=>'asciidoctor-diagram'})
  	end
    Asciidoctor.render_file("index.adoc", :to_dir => "build", :safe => Asciidoctor::SafeMode::UNSAFE, :attributes=> {'sectnums'=>'','stylesheet'=>'main.css','stylesdir'=>'stylesheets/','icons' =>'font','idprefix' => '', 'idseparator' => '-', 'copycss' => '', 'source-highlighter' => 'coderay@', 'sectanchors' => '', 'doctype' => 'book', 'eruby'=>'erubis','toc' => 'left', 'toclevels' => '1', 'revnumber' => '1.0', 'require'=>'asciidoctor-diagram'})
  }
end

guard 'livereload' do
  watch(%r{build/.+\.(css|js|html)$})
end
```

but the diagram blocks convert incorrectly.

give me a favor pls,  thanks a lot

**Comment by mojavelinux** [comment] 2018-11-05 11:39
This issue is a duplicate of https://github.com/asciidoctor/guard-asciidoc/issues/9. Since it pertains to the guard plugin, and not this library directly, I'm closing this one.

**Closed by mojavelinux** 2018-11-05 11:39 UTC
