### ISSUE TITLE
Positional target attribute generate same file name

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor-diagram#304] opened 2020-10-31 01:10 UTC
```
[plantuml,,svg]
.Sequence diagram
----
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections
----
```

```
[plantuml,,svg]
----
@startmindmap
skinparam monochrome true
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
+++ Lubuntu
+++ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
----

[plantuml,,svg]
----
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections
----
```

the upper asciidoctor code will output the same image which is the last diagram when use asciidoctor binary as render, while privewing with asciidoctor.js and kroki, the diagrams outputted individually.

evinonment:
hugo + asciidoctor binary + asciidoctor-diagram

**Comment by pepijnve** [comment] 2021-01-17 16:23
Duplicate of #305

**Closed by pepijnve** 2021-01-17 16:23 UTC
