### ISSUE TITLE
enable numbered captions for generated diagrams

### ISSUE THREAD

**Issue by Smolli** [asciidoctor/asciidoctor-diagram#164] opened 2017-09-14 12:52 UTC
Diagrams should also output the figure caption, so all diagram captions start with (e.g. _Figure 1._). Basically it's the same like inculding the generated SVG or PNG file via the `image::` macro.

Example:
`.Specific caption`
`plantuml::diagram.puml[format="svg"]`

outputs:
\<graphic>
Specific caption

`.Specific caption`
`image::diagram.svg[]`

outputs:
\<graphic>
Figure 1. Specific caption

**Comment by pepijnve** [comment] 2017-09-14 13:11
@Smolli I've tried to reproduce this but I haven't been successful.

```
.This is another caption
image::test.png[]

.This is a caption
plantuml::test.puml[]
```

run through `asciidoctor -r asciidoctor-diagram test.asciidoc` results in this for me

![screen shot 2017-09-14 at 15 12 02](https://user-images.githubusercontent.com/225326/30431506-07e427ba-995f-11e7-8f79-9ee5e49f81f5.png)

**Comment by pepijnve** [comment] 2017-09-14 13:18
Note that generating the captions is actually not handled by the extension itself, asciidoctor core does that. The extension converts the plantuml block or block macro to an image block and then passes that on to core which generates the caption for it.

**Comment by Smolli** [comment] 2017-09-14 13:26
Then, what am I doing wrong? I'm using version 1.5.6.1.

My quick example:

    .Title
    plantuml::test.puml[format="svg"]

    .Title
    image::test.svg[]

generates this:
![output](https://user-images.githubusercontent.com/8377574/30432118-f7d90190-9960-11e7-9e71-6e71dfc27ea3.png)

**Comment by pepijnve** [comment] 2017-09-14 13:29
I wish I could tell you. Perhaps this is influenced by external factors? Could you paste the complete asciidoc document and command line invocation that you're using? That will allow me to reproduce exactly what you're doing. If I get the same results as you do I can get this fixed.

**Comment by Smolli** [comment] 2017-09-14 13:37
The document above is complete. And because I'm running on Windows I'm using a Docker image (based on [this](https://hub.docker.com/r/asciidoctor/docker-asciidoctor/), I just updated some dependencied): 

    FROM fedora
    
    ENV JAVA_HOME /jdk1.8.0_144
    ENV PATH $PATH:$JAVA_HOME/bin:/fopub/bin
    ENV BACKENDS /asciidoctor-backends
    ENV GVM_AUTO_ANSWER true
    ENV ASCIIDOCTOR_VERSION "1.5.6.1"
    
    RUN (curl -s -k -L -C - -b "oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz | tar xfz -)
    
    RUN dnf install -y tar \
        make \
        gcc \
        ruby \
        ruby-devel \
        rubygems \
        graphviz \
        rubygem-nokogiri \
        unzip \
        findutils \
        which \
        wget \
        python-devel \
        zlib-devel \
        libjpeg-devel \
        redhat-rpm-config \
        patch \
        sudo \
      && dnf clean packages
    
    RUN mkdir /fopub \
      && curl -L https://api.github.com/repos/asciidoctor/asciidoctor-fopub/tarball | tar xzf - -C /fopub/ --strip-components=1 \
      && touch /tmp/empty.xml \
      && fopub /tmp/empty.xml \
      && rm /tmp/empty.xml
    
    RUN gem install --no-ri --no-rdoc asciidoctor --version $ASCIIDOCTOR_VERSION \
      && gem install --no-ri --no-rdoc asciidoctor-diagram \
      && gem install --no-ri --no-rdoc asciidoctor-epub3 --version 1.5.0.alpha.6 \
      && gem install --no-ri --no-rdoc rake \
      && gem install --no-ri --no-rdoc epubcheck --version 3.0.1 \
      && gem install --no-ri --no-rdoc kindlegen --version 3.0.1 \
      && gem install --no-ri --no-rdoc asciidoctor-pdf --version 1.5.0.alpha.16 \
      && gem install --no-ri --no-rdoc asciidoctor-confluence \
      && gem install --no-ri --no-rdoc rouge coderay pygments.rb thread_safe epubcheck kindlegen \
      && gem install --no-ri --no-rdoc slim \
      && gem install --no-ri --no-rdoc haml tilt \
      && gem install --no-ri --no-rdoc asciidoctor-revealjs
    
    RUN mkdir $BACKENDS \
      && (curl -LkSs https://api.github.com/repos/asciidoctor/asciidoctor-backends/tarball | tar xfz - -C $BACKENDS --strip-components=1) \
      && easy_install "blockdiag[pdf]" \
      && easy_install seqdiag \
      && easy_install actdiag \
      && easy_install nwdiag
    
    RUN (curl -s get.sdkman.io | bash) \
      && /bin/bash -c "source /root/.sdkman/bin/sdkman-init.sh" \
      && /bin/bash -c "echo sdkman_auto_answer=true > ~/.sdkman/etc/config" \
      && /bin/bash -c -l "sdk install lazybones"
    
    WORKDIR /documents
    VOLUME /documents
    
    CMD ["/bin/bash"]


Finally the command line:

    docker run --rm -v <<your-path>>:/documents/ asciidoc asciidoctor-pdf -r asciidoctor-diagram  -o test.pdf test.adoc

**Comment by pepijnve** [comment] 2017-09-14 13:42
The backend might have something to do with it. I was testing with the HTML5 backend; you're using the PDF one. The caption is assigned to the block in the backend independent part of asciidoctor, but it might be the case that the PDF backend doesn't use this for the blocks asciidoctor-diagram is producing. That should be easy enough to figure out.

**Comment by Smolli** [comment] 2017-09-14 13:47
Calling `asciidoctor` instead of `asciidcotor-pdf` doesn't change anything. The HTML does also not contain a numbering.

    <body class="article">
    <div id="header">
    </div>
    <div id="content">
    <div class="imageblock">
    <div class="content">
    <img src="test.svg" alt="Title" width="48" height="188">
    </div>
    <div class="title">Title</div>
    </div>
    <div class="imageblock">
    <div class="content">
    <img src="test.svg" alt="test">
    </div>
    <div class="title">Figure 1. Title</div>
    </div>
    </div>
    <div id="footer">
    <div id="footer-text">
    Last updated 2017-09-14 13:24:29 UTC
    </div>
    </div>
    </body>

**Comment by pepijnve** [comment] 2017-09-14 13:58
I figured out what's happening. I had accidentally tested with asciidoctor 1.5.5, while you were using 1.5.6.1. In 1.5.5 the assignment of captions to image blocks happened after extension processing (https://github.com/asciidoctor/asciidoctor/blob/v1.5.5/lib/asciidoctor/parser.rb#L913). Since 1.5.6 this is only done for image blocks, not for image blocks generated by extensions (https://github.com/asciidoctor/asciidoctor/blob/v1.5.6/lib/asciidoctor/parser.rb#L559).

@mojavelinux was that change intentional? If so, should I call `block.assign_caption((attributes.delete 'caption'), 'figure')` from within asciidoctor-diagram to fix this?

**Comment by pepijnve** [comment] 2017-09-14 14:19
@Smolli The commit that's referenced above fixes this. If @mojavelinux confirms this is the correct way to fix this I'll go ahead and merge this and make a new release.

**Comment by Smolli** [comment] 2017-09-14 16:32
Thank you very much!

**Comment by mojavelinux** [comment] 2017-09-14 19:36
@pepijnve I did not mean to break this functionality. As I continue to clean up the parser, it's clear that the logic shouldn't have been where it was. I do agree the right approach is to call assign_caption from within the extension, as it should be kept with the creation of the image block. It's also safe to call it multiple times as the value is cached, so it will work fine with 1.5.5 too.

In fact, all this logic https://github.com/asciidoctor/asciidoctor/blob/v1.5.5/lib/asciidoctor/parser.rb#L909-L919 should be moved to the [create_image_block](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb#L159-L165) method. Though I'm thinking that Asciidoctor Diagram should probably just do all this logic until that method stabilizes more.

(I might even suggest just defining / overriding this method so that it does exactly what you need and eventually we can remove the override once core provides all the right logic).

Let's make sure to have a test so that changes to core don't break this again (such as if I were to rename the method or something).

**Comment by mojavelinux** [comment] 2017-09-14 19:37
This problem has been reported in a couple of places now...so I'll go find those and route them to this issue.

**Closed** 2017-09-28 07:02 UTC
