### ISSUE TITLE
release 1.5.4.1 seems to cause problems with reveal.js backend

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-diagram#161] opened 2017-09-01 20:32 UTC
I use the asciidoctor reveal.js backend to generate presentations and today I noticed that when I use asciidoctor-diagram v 1.5.4.1, the output is broken (background images don't work for instance).

v 1.5.4 works fine. 

I tried to find the reason by diffing the two version, but it somehow doesn't make sense...

PS: I use the asciidoctorj-version

**Comment by rdmueller** [comment] 2017-09-05 07:30
I guess it is related to this issue
https://github.com/asciidoctor/asciidoctor-reveal.js/issues/132

and might be resolved by now. I will retest it asap

**Comment by mojavelinux** [comment] 2017-09-05 07:51
I'm definitely interested to know what's going on. If core did break Asciidoctor Diagram, that means an additional test is needed.

**Comment by pepijnve** [comment] 2017-09-06 18:16
@rdmueller I did a quick test with this `Gemfile.lock`.

```
GEM
  remote: https://rubygems.org/
  specs:
    asciidoctor (1.5.6.1)
    asciidoctor-diagram (1.5.4.1)
      asciidoctor (~> 1.5.0)
    asciidoctor-revealjs (1.0.2)
      asciidoctor (~> 1.5.4)
      slim (~> 3.0.6)
      thread_safe (~> 0.3.5)
    slim (3.0.8)
      temple (>= 0.7.6, < 0.9)
      tilt (>= 1.3.3, < 2.1)
    temple (0.8.0)
    thread_safe (0.3.6)
    tilt (2.0.8)

PLATFORMS
  ruby

DEPENDENCIES
  asciidoctor (= 1.5.6.1)
  asciidoctor-diagram (= 1.5.4.1)
  asciidoctor-revealjs

BUNDLED WITH
   1.13.6
```

and this input document

```
= Title Slide

== Slide One

[plantuml]
----
A -> B
----
```

Then I ran `bundle exec asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0 -r asciidoctor-diagram presentation.adoc`. The end result was a working presentation. Not sure what's going wrong for you since things seem to work correctly for me. Perhaps this is an issue in asciidoctorj?

**Comment by rdmueller** [comment] 2017-09-06 19:46
sorry, I am not a ruby guy. I used the asciidoctorj versions together with gradle.

Here is my input file:

```
= Test

image::https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg[canvas,size=contain]

painless docs for developers

== Features

image::https://upload.wikimedia.org/wikipedia/commons/b/b2/Hausziege_04.jpg[canvas,size=contain]

[%step]
* Foo
* Bar
* World
```

the image should be displayed as background, but was displayed as a normal image with v1.5.4.1 .
Maybe my input file is not clean, but the simple switch of the version changed the output in my (rather large) example.

sorry, but I currently lack the time to come up with a proper example to reproduce the problem - in two weeks, I could give you one.

**Comment by pepijnve** [comment] 2017-09-06 19:57
Your example has me a bit confused. There's nothing in there that involves asciidoctor-diagram. What makes you think 1.5.4.1 is causing this?

**Comment by mojavelinux** [comment] 2017-09-06 20:14
Aha. I see what's going on now. There was a change in core that broke this
feature in the reveal converter. There is a fix for it in the master
branch. (If you want to stay on a release of the reveal converter, you have
to set the Asciidoctor version to 1.5.5).

The fact that the image was a diagram was a red herring. That had nothing
to do with this problem.

**Comment by pepijnve** [comment] 2017-09-06 20:17
Ok, so the root cause is indeed asciidoctor/asciidoctor-reveal.js#132. as @rdmueller stated. I'm going to close this issue since no further action is required in this project.

**Closed by pepijnve** 2017-09-06 20:17 UTC

**Comment by mojavelinux** [comment] 2017-09-06 20:21
+1

Sorry for the noise.

**Comment by rdmueller** [comment] 2017-09-06 23:11
yes, sorry for the noice and thanx for the help!

**Comment by pepijnve** [comment] 2017-09-07 07:02
No worries. Glad we got to the bottom of it.
