### ISSUE TITLE
Syntrax diagrams SVG dimensions problem -- cropped diagrams

### ISSUE THREAD

**Issue by inponomarev** [asciidoctor/asciidoctor-diagram#261] opened 2020-01-27 07:01 UTC
Hello, 

the way the SVG output of Syntrax is embedded into HTML is not working correctly in all browsers.

For example definition +++[syntrax,script,svg,opts=interactive]+++ turns into <svg ... width="468" height="271" > </svg> (see example [here](https://courseorchestra.github.io/celesta/#CelestaSQL))

But diagrams appear to be cropped in IPhone's Safari and in print preview of Firefox, see screenshot below:

![изображение](https://user-images.githubusercontent.com/20153286/73155414-bb2cf780-40eb-11ea-8f93-b1e81906fee9.png)

**Comment by pepijnve** [comment] 2020-03-03 19:55
I did some quick checks and this seems to be caused by the CSS style that gets applied to get containing `object`. If I disable `max-width: 100%` for instance, then it seems to render correctly.

I'm not really a CSS expert I'm afraid so I'm not sure what the 'correct' fix is here.

**Comment by mojavelinux** [comment] 2020-03-05 10:37
The max-width is important to prevent the object from overflowing the bounds. The problem here seems to be that we're hitting a browser bug, because the described behavior is not to spec.

You could try opts=inline instead of opts=interactive. See what that gives you.

**Comment by pepijnve** [comment] 2020-03-05 11:41
@mojavelinux It wasn't clear to me what should actually happen until I read through https://css-tricks.com/scale-svg/.
My conclusion from reading that is that we need to pick an option and massage the generated SVG accordingly. What's not clear yet is which sizing option we actually want.

**Comment by pepijnve** [comment] 2020-10-01 09:16
@inponomarev I think this should be fixed in the latest release. Feel free to reopen this issue if the problem still occurs.

**Closed by pepijnve** 2020-10-01 09:16 UTC
