### ISSUE TITLE
support for python3 version of blockdiag (and other tools)

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-diagram#98] opened 2016-03-13 00:33 UTC
Under Debian, ```python3``` ```blockdiag``` installs as ```blockdiag3```. Could that be also discovered on the PATH? Thanks

**Comment by pepijnve** [comment] 2016-03-13 16:04
Fix for this will be in included in 1.4.1. In the meantime the solution provided in #97 can be used as a workaround.

**Closed** 2016-03-13 16:04 UTC

**Comment by ioannisstavrakakis** [comment] 2023-06-14 12:36
I also get this error, in 3.0.0.
The [tip](https://github.com/asciidoctor/asciidoctor-diagram/issues/97#issuecomment-195946560) does not work for me.

**Comment by pepijnve** [comment] 2023-06-14 20:51
I'm afraid I can't reproduce this. I installed blockdiag on macOS and ensured the binary is named `blockdiag3`. The extension finds and uses it without any issues.

**Comment by ioannisstavrakakis** [comment] 2023-06-15 05:58
Sorry, I forgot to mention I am using Windows.

**Comment by pepijnve** [comment] 2023-06-15 06:54
Ok, could you open a new issue for this? Please add some more details describing your environment. I would need to know where you have blockdiag installed, what the value of the `PATH` environment variable is, and what the exact filename of the blockdiag executable is, including the extension.
