### ISSUE TITLE
Positional target attribute output same filename

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor-diagram#305] opened 2020-10-31 01:12 UTC
```
[plantuml,,svg]
.Sequence diagram
----
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections
----

[plantuml,,svg]
----
@startmindmap
skinparam monochrome true
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
+++ Lubuntu
+++ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
----

[plantuml,,svg]
----
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections
----
```

the upper asciidoctor code will output the same image which is the last diagram when use asciidoctor binary as render, while privewing with asciidoctor.js and kroki, the diagrams outputted individually.

evinonment:
hugo + asciidoctor binary + asciidoctor-diagram

**Comment by pepijnve** [comment] 2020-10-31 14:08
I can reproduce this locally, but I don't think there's much I can do about this. The positional attributes are actually not mapped the way you think they are. As far as I can tell the parsing of attribute lists will not allow you to skip positional attributes. What the extension actually receives is
```
1 => "plantuml"
2 => "svg"
```
while you're expecting it to receive
```
1 => "plantuml"
2 => nil
3 => "svg"
```

The consequence is that asciidoctor-diagram is receiving `svg ` as target value twice and the target of the block is used to derive the output filename.

The simplest fix for this is to use `format="svg"` instead or set the format at the document level using `:plantuml-format: svg`.

**Comment by pepijnve** [comment] 2020-10-31 14:12
@mojavelinux is there a difference between asciidoctor and asciidoctor.js in how it parses an attribute list like `[plantuml,,svg]` when it comes to handling the middle empty attribute?

**Comment by edl7878** [comment] 2020-11-01 01:56
@pepijnve  Got it. Thanks.

**Comment by mojavelinux** [comment] 2020-11-01 06:19
@pepijnve Not to my knowledge. It's the same code. The variation probably comes from the kroki extension itself.

**Comment by mojavelinux** [comment] 2020-11-01 06:34
This actually looks like a parsing bug. The parser allows the first position to be blank (e.g., `,ruby`), but not any other position. It should retain the positional offset so it's consistent with the number of delimiters. Please file an issue in core.

**Comment by mojavelinux** [comment] 2020-11-01 07:56
https://github.com/asciidoctor/asciidoctor/issues/3813

**Comment by pepijnve** [comment] 2020-11-01 14:59
Thanks for logging this @mojavelinux. @edl7878 once the asciidoctor issue has been resolved the workaround(s) I mentioned will no longer be necessary.

**Closed by pepijnve** 2020-11-01 14:59 UTC
