### ISSUE TITLE
[meme] 'identify failed : <width>' on Gitlab CI

### ISSUE THREAD

**Issue by bcouetil** [asciidoctor/asciidoctor-diagram#205] opened 2018-12-22 13:47 UTC
Hello,

I've been trying the meme extension, working great on my Windows system.

But I've a problem when generating in my gitlab CI pipeline :
`asciidoctor-diagram: ERROR: Failed to generate image: identify failed: 1920`

1920 happens to be the width of my image.

I'm installing ImageMagick using :
`$ apt-get update -qq && apt-get install -qq --assume-yes imagemagick`

I found this piece of code in the source :
`dimensions = Cli.run(identify, '-format', '%w %h', bg_img)[:out].match(/(?<w>\d+) (?<h>\d+)/)`

So I reproduced the command after installing ImageMagick and before using Asciidoctor, and it seems to work great :
```
$ identify -format "%w %h" src/docs/asciidoc/images/dont-reboot-it-just-patch.jpg
1920 1080
```

Tried on another image, this time a smaller PNG, same problem.

**Comment by pepijnve** [comment] 2018-12-22 16:59
The code runs that command and then checks the exit code. It experts it to return 0. If that’s not the case the command is considered to have failed and the output is printed. I think that’s what you’re seeing. No idea why `identify` is returning an error exit code. I’ll have to reread the man pages.

**Comment by pepijnve** [comment] 2019-01-19 15:17
I think I've finally been able to trace the root cause of this. In a nutshell JRuby doesn't implement spawn very reliably. Since https://github.com/jruby/jruby/commit/a467bc525f62c56696ec314aaf0d719947560798 there are cases where it joins all the arguments into a single string and uses the standard shell to execute that command. That has completely different semantics than calling spawn.

As a workaround, on Jruby, I'm going to use the Java infrastructure (ProcessBuilder) to call external processes instead.

**Comment by bcouetil** [comment] 2019-01-19 18:18
Nice, just tell me when and how I can test it, I'll gladly do it 😄

**Comment by pepijnve** [comment] 2019-01-20 15:01
@bcouetil could you confirm that you're having this problem with JRuby?  If not, which Ruby implementation are you using? Just want to make sure it's really fixed before I close this.

**Comment by bcouetil** [comment] 2019-01-20 16:30
@pepijnve yes I suppose, since this is in my Maven dependencies : 
```
<dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctorj-pdf</artifactId>
    <version>1.5.0-alpha.16</version>
</dependency>
<dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctorj-diagram</artifactId>
    <version>1.5.9</version>
</dependency>
<!-- comment to use the default version -->
<dependency>
    <groupId>org.jruby</groupId>
    <artifactId>jruby-complete</artifactId>
    <version>9.1.17.0</version>
</dependency>
```

**Comment by pepijnve** [comment] 2019-01-20 19:34
Could you give asciidoctor-diagram 1.5.12 a go? Should fix the problem.

**Comment by bcouetil** [comment] 2019-01-21 10:01
Pardon my noobness, but I need your help, what do I change in the dependencies told earlier, and where to find the new jar (since latest asciidoctorj-maven is 1.5.11 on Central) 😄

**Comment by pepijnve** [comment] 2019-01-21 10:16
I'm not sure who builds that jar. I think maybe @robertpanzer can help.

**Comment by robertpanzer** [comment] 2019-01-22 14:49
I just released asciidoctorj-diagram 1.5.12.
It should be already on bintray and hit Maven Central soon.

**Comment by pepijnve** [comment] 2019-03-07 12:29
@bcouetil did the new asciidoctorj-diagram build fix this for you?

**Comment by bcouetil** [comment] 2019-03-07 15:35
At the time I was waiting for the maven package availability. I just tested, this is working great, thanks !

I obtain an image with a [weird font](https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html#/meme-as-code), but I guess that the meme font is not available on Gitlab, and that's another story 😸 

We can close this.

**Closed** 2019-03-07 15:36 UTC

**Comment by pepijnve** [comment] 2019-03-07 15:39
Not sure there's much that can be done about the font. The image is generated using the imagemagick `convert` command. By default it gets passed the parameter `-font Impact`. I'm not sure what the fallback strategy is in `convert` if the requested font can not be found. Looks like some default sans-serif font.

**Comment by bcouetil** [comment] 2019-03-07 17:23
You gave me just the piece of information I needed my friend, I have a solution now 😃 

For anyone stumbling upon this thread, here is a prerequisite on unix systems (you may need some `sudo` that gitlab doesn't) : 

```
# to have ttf package available
$ echo "deb http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty multiverse \ndeb http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates multiverse \ndeb http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse" | tee /etc/apt/sources.list.d/multiverse.list

# to accept ttf license automatically
$ echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections

# the actual apt-get
$ apt-get update -qq && apt-get install -qq --assume-yes --allow-unauthenticated imagemagick ttf-mscorefonts-installer
```

**Comment by pepijnve** [comment] 2019-03-07 17:25
Alternative is to specify the font you want to use instead via the `font` attribute.
The default is `Impact` since that's the de facto standard meme font.
